sudo: required
latex: false
os:
  - linux
  - osx
compiler:
  - gcc
  #- clang

#matrix:
#  allow_failures:
#    - os: linux

dist: trusty

language: r

cache: packages

r:
  - release

before_install:
  - export itkrrel=0.4.12
  - export gh_user=stnava
  - export ANTsRCorerel=0.4.2.1
  - export reldir=latest
  - export antsrrel=0.6.1
  - Rscript -e 'install.packages("RcppArmadillo")'
  - wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
  - chmod +x antsr_travis.sh
  - . ./antsr_travis.sh
  - rm antsr_travis.sh
  - cat DESCRIPTION

